analyzer:
  skip_excluded: true
  enabled_package_managers: [NPM]
excludes:
  scopes:
    - pattern: "devDependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "These are packages used for the development, testing and build process and are not required at runtime."
