services:
  repository:
    image: mcr.microsoft.com/playwright:v1.54.2
    working_dir: /opt/repository
    ports:
      - "5173:5173"
      - "4173:4173"
    volumes:
      - ./:/opt/repository:cached
      - node-modules:/opt/repository/node_modules
      - patterns-node-modules:/opt/repository/patterns/node_modules
      - react-router-node-modules:/opt/repository/react-router/node_modules
      - templates-node-modules:/opt/repository/templates/node_modules
volumes:
  node-modules:
  patterns-node-modules:
  react-router-node-modules:
  templates-node-modules:
