name: 'Build'

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image to be used in workflow.'
        required: true
        type: string

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Lint'
        run: yarn lint
  patterns:
    name: 'Patterns'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: yarn build:patterns
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-patterns
          path: ./patterns/dist/
  angular:
    name: 'Angular'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: yarn build:angular --base-href /examples/angular
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-angular
          path: ./frameworks/angular/dist/angular/browser/
  next-js:
    name: 'Next.js'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: NEXT_PUBLIC_BASE_PATH=/examples/next-js yarn build:next-js
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-next-js
          path: ./frameworks/next-js/dist/
  react:
    name: 'React'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: REACT_PUBLIC_BASE_PATH=/examples/react yarn build:react
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-react
          path: ./frameworks/react/dist/
  react-router:
    name: 'React Router'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: yarn build:react-router
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-react-router
          path: ./frameworks/react-router/build/client/examples/react-router/
  vanilla-js:
    name: 'Vanilla JS'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: VANILLA_JS_PUBLIC_BASE_PATH=/examples/vanilla-js yarn build:vanilla-js
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-vanilla-js
          path: ./frameworks/vanilla-js/dist/
  vue:
    name: 'Vue'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: VUE_PUBLIC_BASE_PATH=/examples/vue yarn build:vue
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-vue
          path: ./frameworks/vue/dist/
  templates:
    name: 'Templates'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: yarn build:templates
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-templates
          path: ./templates/dist/
