name: 'Build'

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image to be used in workflow.'
        required: true
        type: string

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Lint'
        run: yarn lint
  patterns:
    name: 'Patterns'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: yarn build:patterns
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-patterns
          path: ./patterns/dist/
  react-router:
    name: 'React Router'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: yarn build:react-router
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-react-router
          path: ./react-router/build/client/examples/react-router/
  templates:
    name: 'Templates'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: yarn build:templates
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-templates
          path: ./templates/dist/
