name: 'Build'

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image to be used in workflow.'
        required: true
        type: string

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Lint'
        run: npm run lint
  angular:
    name: 'Angular'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build:ci --workspace=@porsche-design-system/angular
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-angular
          path: ./frameworks/angular/dist/
  astro:
    name: 'Astro'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build:ci --workspace=@porsche-design-system/astro
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-astro
          path: ./frameworks/astro/dist/
  next-js:
    name: 'Next.js'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build:ci --workspace=@porsche-design-system/next-js
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-next-js
          path: ./frameworks/next-js/dist/
  react:
    name: 'React'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build:ci --workspace=@porsche-design-system/react
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-react
          path: ./frameworks/react/dist/
  react-router:
    name: 'React Router'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build:ci --workspace=@porsche-design-system/react-router
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-react-router
          path: ./frameworks/react-router/build/client/examples/react-router/
  vanilla-js:
    name: 'Vanilla JS'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build:ci --workspace=@porsche-design-system/vanilla-js
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-vanilla-js
          path: ./frameworks/vanilla-js/dist/
  vue:
    name: 'Vue'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build:ci --workspace=@porsche-design-system/vue
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-vue
          path: ./frameworks/vue/dist/
  patterns:
    name: 'Patterns'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build:ci --workspace=@porsche-design-system/patterns
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-patterns
          path: ./patterns/dist/
  templates:
    name: 'Templates'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build:ci --workspace=@porsche-design-system/templates
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-templates
          path: ./templates/dist/
