name: 'Deploy'

on:
  workflow_call:
    inputs:
      gh-pages-slug:
        description: 'Deploy target slug (e.g. "nightly", "pr-123", "v4"), used as the gh-pages folder.'
        required: true
        type: string

permissions:
  contents: write

env:
  BRANCH_BASE_PATH: ${{ inputs.gh-pages-slug }}

jobs:
  deploy:
    name: 'Examples'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: 'gh-pages'
      - name: 'Clean'
        run: |
          rm -rf "./${{ env.BRANCH_BASE_PATH }}"
        shell: bash
      - name: 'Download artifact "Patterns"'
        uses: actions/download-artifact@v8
        with:
          name: build-patterns
          path: "./${{ env.BRANCH_BASE_PATH }}/patterns/"
      - name: 'Download artifact "Angular"'
        uses: actions/download-artifact@v8
        with:
          name: build-angular
          path: "./${{ env.BRANCH_BASE_PATH }}/angular/"
      - name: 'Download artifact "Astro"'
        uses: actions/download-artifact@v8
        with:
          name: build-astro
          path: "./${{ env.BRANCH_BASE_PATH }}/astro/"
      - name: 'Download artifact "Next.js"'
        uses: actions/download-artifact@v8
        with:
          name: build-next-js
          path: "./${{ env.BRANCH_BASE_PATH }}/next-js/"
      - name: 'Download artifact "PDS UI Testing"'
        uses: actions/download-artifact@v8
        with:
          name: build-pds-ui-testing
          path: "./${{ env.BRANCH_BASE_PATH }}/pds-ui-testing/"
      - name: 'Download artifact "React"'
        uses: actions/download-artifact@v8
        with:
          name: build-react
          path: "./${{ env.BRANCH_BASE_PATH }}/react/"
      - name: 'Download artifact "React Router"'
        uses: actions/download-artifact@v8
        with:
          name: build-react-router
          path: "./${{ env.BRANCH_BASE_PATH }}/react-router/"
      - name: 'Download artifact "Vanilla JS"'
        uses: actions/download-artifact@v8
        with:
          name: build-vanilla-js
          path: "./${{ env.BRANCH_BASE_PATH }}/vanilla-js/"
      - name: 'Download artifact "Vue"'
        uses: actions/download-artifact@v8
        with:
          name: build-vue
          path: "./${{ env.BRANCH_BASE_PATH }}/vue/"
      - name: 'Download artifact "Templates"'
        uses: actions/download-artifact@v8
        with:
          name: build-templates
          path: "./${{ env.BRANCH_BASE_PATH }}/templates/"
      - name: 'Deploy'
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -m "Automated deployment to GitHub Pages (${{ github.ref_name }}): ${{ github.sha }}" --allow-empty
          git push origin gh-pages --force
        shell: bash
