name: 'Test (Patterns)'

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image to be used in workflow.'
        required: true
        type: string

jobs:
  e2e-patterns:
    name: 'E2E (Patterns)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Download artifact'
        uses: actions/download-artifact@v5
        with:
          name: build-patterns
          path: ./patterns/dist
      - name: 'E2E'
        run: yarn test:e2e:patterns
        shell: bash
  a11y-patterns:
    name: 'A11y (Patterns)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Download artifact'
        uses: actions/download-artifact@v5
        with:
          name: build-patterns
          path: ./patterns/dist
      - name: 'A11y'
        run: yarn test:a11y:patterns
        shell: bash
  # vrt:
  #   name: 'VRT'
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ${{ inputs.image }}
  #     options: --user 1001
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       shardIndex: [ 1, 2, 3 ]
  #       shardTotal: [ 3 ]
  #   steps:
  #     - name: 'Checkout'
  #       uses: actions/checkout@v4
  #     - name: 'Setup and install'
  #       uses: ./.github/actions/install
  #     - name: 'Download build artifact'
  #       uses: actions/download-artifact@v5
  #       with:
  #         name: examples
  #         path: ./dist
  #     - name: 'VRT'
  #       run: yarn test:vrt:patterns --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
  #       shell: bash
  #     - name: 'VRT Regression'
  #       if: failure()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: regression-vrt-patterns-${{ matrix.shardIndex }}
  #         path: ./tests/vrt/test-results
