name: 'Test'

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image to be used in workflow.'
        required: true
        type: string

permissions:
  contents: read

jobs:
  e2e-angular:
    name: 'E2E (Angular)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'E2E'
        run: npm run test:e2e:angular
        shell: bash
  e2e-astro:
    name: 'E2E (Astro)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'E2E'
        run: npm run test:e2e:astro
        shell: bash
  e2e-next-js:
    name: 'E2E (Next.js)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'E2E'
        run: npm run test:e2e:next-js
        shell: bash
  e2e-react:
    name: 'E2E (React)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'E2E'
        run: npm run test:e2e:react
        shell: bash
  e2e-react-router:
    name: 'E2E (React Router)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'E2E'
        run: npm run test:e2e:react-router
        shell: bash
  e2e-vanilla-js:
    name: 'E2E (Vanilla JS)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'E2E'
        run: npm run test:e2e:vanilla-js
        shell: bash
  e2e-vue:
    name: 'E2E (Vue)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'E2E'
        run: npm run test:e2e:vue
        shell: bash
  e2e-patterns:
    name: 'E2E (Patterns)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Download artifact'
        uses: actions/download-artifact@v6
        with:
          name: build-patterns
          path: ./patterns/dist
      - name: 'E2E'
        run: npm run test:e2e:patterns
        shell: bash
  a11y-patterns:
    name: 'A11y (Patterns)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Download artifact'
        uses: actions/download-artifact@v6
        with:
          name: build-patterns
          path: ./patterns/dist
      - name: 'A11y'
        run: npm run test:a11y:patterns
        shell: bash
  vrt-patterns:
   name: 'VRT (Patterns)'
   runs-on: ubuntu-latest
   container:
     image: ${{ inputs.image }}
     options: --user 1001
   steps:
     - name: 'Checkout'
       uses: actions/checkout@v5
     - name: 'Install'
       uses: ./.github/actions/install
     - name: 'Download artifact'
       uses: actions/download-artifact@v6
       with:
         name: build-patterns
         path: ./patterns/dist
     - name: 'VRT'
       run: npm run test:vrt:patterns
       shell: bash
     - name: 'VRT Regression'
       if: failure()
       uses: actions/upload-artifact@v5
       with:
         name: regression-vrt-patterns
         path: ./patterns/tests/vrt/test-results
